name: Checks

on:
  push:
    branches:
      - main

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup latest Deno version
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run Deno fmt
        run: deno fmt --check **/*.ts

      - name: Run Deno lint
        run: deno lint **/*.ts

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup latest Deno version
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run Deno test
        run: |
          deno run -A index.ts &
          sleep 10
          deno test -A
        env:
          MAILGUN_TO: ${{ secrets.MAILGUN_TO }}
          MAILGUN_KEY: ${{ secrets.MAILGUN_KEY }}
          MAILGUN_REGION: ${{ secrets.MAILGUN_REGION }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}